generate should return string rather than Cstuct.t
mirage/mirage-skeleton pull request #388
Opened 2024-03-23 18:02 UTC by oemmerson

Previously building these examples would fail with the error

```
Error: This expression has type int -> Cstruct.t
       but an expression was expected of type int -> string
       Type Cstruct.t is not compatible with type string
make[1]: *** [build] Error 1
```

2024-03-23 20:35 UTC, reynir commented
Thank you for your PR! The recent randomconv.0.2.0 release changed the expected type from `Cstruct.t` to `string` in anticipation of an upcoming mirage-crypto release that brings a cstruct->string overhaul.

I would say the preferred way forward is to set an upper bound on randomconv<0.2.0 for now.

2024-03-23 21:25 UTC, oemmerson commented
@reynir Thanks for explaining. I've reverted the original commit, added the upper bound you suggested and checked the kernel's build without issue.

2024-03-24 07:40 UTC, reynir requested changes
Thanks! This is great. One thing though: The `~max` argument to `Mirage.package` is *exclusive* meaning `~max:"0.1.3"` is `<"0.1.3"`. I forget this all the time, and the documentation is not-so-helpfully referring to some Functoria documentation (I will open an issue on that).

2024-03-24 07:40 UTC, reynir commented on tutorial/lwt/echo_server/config.ml
> +  let packages = [ package "duration"; package ~max:"0.1.3" "randomconv" ] in
```suggestion
  let packages = [ package "duration"; package ~max:"0.2.0" "randomconv" ] in
```

2024-03-24 07:40 UTC, reynir commented on tutorial/lwt/timeout1/config.ml
> +    ~packages:[ package "duration"; package ~max:"0.1.3" "randomconv" ]
```suggestion
    ~packages:[ package "duration"; package ~max:"0.2.0" "randomconv" ]
```

2024-03-24 07:40 UTC, reynir commented on tutorial/lwt/timeout2/config.ml
> +    ~packages:[ package "duration"; package ~max:"0.1.3" "randomconv" ]
```suggestion
    ~packages:[ package "duration"; package ~max:"0.2.0" "randomconv" ]
```

2024-03-25 07:10 UTC, reynir approved these changes

2024-03-25 07:11 UTC, merged

2024-03-25 07:11 UTC, reynir commented
Thanks a lot!